[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "doc_automator"
version = "0.1.0"
description = "Outil pour remplir automatiquement les docstrings depuis un PDF d'énoncé"
dependencies = [
    "pymupdf",
]